global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.CQRS;
global using Coach.API.Data.Models;
global using Coach.API.Exceptions;
global using FluentValidation;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.Handler;